[env:esp32dev]
platform = espressif32 @ 6.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient @ ^2.8
    fastled/FastLED @ ^3.6.0
    bblanchon/ArduinoJson @ ^6.21.3
